//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectionEntity : DbContext
    {
        public ConnectionEntity()
            : base("name=ConnectionEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Pasport> Pasports { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Relative> Relatives { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<TypeUser> TypeUsers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Representative> Representatives { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
    }
}
