//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasport
    {
        public int Id { get; set; }
        public int Series { get; set; }
        public int Number { get; set; }
        public string WhoGave { get; set; }
        public System.DateTime DateGet { get; set; }
        public string Address { get; set; }
        public string DevisionCode { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
