//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Representative
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public string PlaceOfWork { get; set; }
        public string Residence { get; set; }
        public string HomePhone { get; set; }
        public int StudentId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Student Student { get; set; }
        public virtual Type Type1 { get; set; }
    }
}
